### PR TITLE
Allow installing HLS from source

### LINKED ISSUE #12: Upgrade to GHC 9.2.5
https://discourse.haskell.org/t/ghc-9-2-5-released/5275

We'll either have to wait for HLS to release new binaries, or produce an image without HLS. (Compiling from source didn't work for us: #8.)

### LINKED ISSUE #13: Upgrade to GHC 9.4.3
https://discourse.haskell.org/t/ghc-9-4-3-is-now-available/5268

Same note about HLS as #12.

### PR DESCRIPTION
**Pull request by tfausak**
Alternative to #14. Would fix #12. Also would fix #13. 

---

- [x] I manually tested the code locally to make sure that it works.
- [x] If there is documentation, I made sure it's accurate and up to date.
- [x] If possible, I wrote automated tests for the new behavior.

### CODE REVIEW

**Comment by tfausak** [comment]
So, what changed here?

- I moved the "configure Cabal" block immediately after "install Cabal". This is because compiling HLS from source uses Cabal, so we need it to be configured before compiling. 
- I did the same thing for Stack, just for symmetry. 
- I upgraded to GHC 9.2.5. 
- Same for GHC 9.4.3. 
- I changed the HLS installation to look for `HLS_VERSION` values that look like commit hashes. If it's a commit hash, it will try to compile from source. Otherwise it will install like it used to before. 
- I reformatted the Dockerfile to indent conditionals, which hopefully makes things a little clearer.

**Review by codygman — APPROVED** [review]

**Comment by tfausak** [comment]
ARM build ran out of memory:

> [Container] 2022/11/10 20:48:56 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker build --build-arg GHC_VERSION="$GHC_VERSION" --build-arg HLS_VERSION="$HLS_VERSION" --tag "$tag" .. Reason: exit status 9

I think I can give it more.

**Comment by tfausak** [comment]
Actually AMD failed for the same reason. I changed both of them to have 16 GB of RAM and 8 vCPUs. I restarted the GHC 9.4.3 builds to see if they succeed. If they do, I'll restart all the builds.

**Comment by tfausak** [comment]
Unfortunately that failed too. I can configure a larger machine for AMD, but not for ARM. I'm going to try setting `--jobs=1`.

**Comment by tfausak** [comment]
That failed again for both AMD and ARM. I think this approach isn't going to work for us. HLS simply requires more resources to build than we are able to provide. 

There is another step up in CodeBuild for the AMD machines, but we're already at the top for the ARM machines. I suppose it's possible that we could build for ARM using emulation on a giant AMD machine, but that seems like more trouble than it's worth at this point.

**Comment by tfausak** [comment]
It would use [`docker buildx build --platform=...`](https://docs.docker.com/engine/reference/commandline/buildx_build/#platform). Actually now that I look at it, it doesn't seem so bad. Let me give it a try.

**Comment by tfausak** [comment]
I think that my code is all correct, but I keep getting this error with the ARM64 build:

> Error while loading /usr/local/sbin/apt-get: No such file or directory

I have no idea how to fix it.

**Comment by tfausak** [comment]
Closing in favor of #16.

**Pull request closed without merging**
