### PR TITLE
Upgrade to HLS 1.8.0.0

### PR DESCRIPTION
**Pull request by tfausak**
https://discourse.haskell.org/t/ann-haskell-language-server-1-8-0-0-released/5053

### CODE REVIEW

**Comment by tfausak** [comment]
The ARM64 binaries are only available for Darwin: https://downloads.haskell.org/hls/haskell-language-server-1.8.0.0/

**Comment by codygman** [comment]
> The ARM64 binaries are only available for Darwin: https://downloads.haskell.org/hls/haskell-language-server-1.8.0.0/

That is very unfortunate 😞

**Comment by tfausak** [comment]
Someone asked about it on Discourse: https://discourse.haskell.org/t/ann-haskell-language-server-1-8-0-0-released/5053/2

**Comment by tfausak** [comment]
Apparently the build timed out. There should be binaries as soon as it finishes: https://discourse.haskell.org/t/ann-haskell-language-server-1-8-0-0-released/5053/6

**Comment by tfausak** [comment]
Binaries were uploaded and added to GHCup: https://discourse.haskell.org/t/ann-haskell-language-server-1-8-0-0-released/5053/16

**Pull request merged**
