### PR TITLE
Update ghc 9.8.2

### PR DESCRIPTION
**Pull request by codygman**
This one should be easy to approve and get us the new docker images. Then I can test and see if I can just change over without the amazonka changes @darycabrera and I talked about this morning.

### CODE REVIEW

**Review by darycabrera — APPROVED** [review]

**Review by MengZhang — APPROVED** [review]

**Review by davey4 — APPROVED** [review]

**Comment by codygman** [comment]
Okay, for some reason the manifest is expecting older versions. I think this might be some code build specific thing.

**Comment by codygman** [comment]
No, the checks are bugged. In the [checks tab](https://github.com/acilearning/docker-haskell/pull/78/checks) you see everything is passing.

But for some reason manifest 9.6.4 and manifest 9.8.1 are expected. I don't have github admin rights, do any of you @davey4 @darycabrera @MengZhang?

If not, @Robots71 can you merge this PR if you have admin?

**Comment by davey4** [comment]
I don't think any of us have admin rights. @melittleman, @Broady-98, @jamespepper81?

**Review by Broady-98 — APPROVED** [review]
approved

**Pull request merged**
